repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: .venv/bin/ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: Ruff Format
        entry: .venv/bin/ruff format
        language: system
        types: [python]
        pass_filenames: false